language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

install:
  - make deps

script:
  - make setup
  - make test

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true