# -----------------------------------------------------------------------------
# Description: Travis CI buildfile
# Author(s): retgits
# Last updated: 2019-04-19
# 
# This software may be modified and distributed under the terms of the
# MIT license. See the LICENSE file for details.
# -----------------------------------------------------------------------------

# Set language
language: go

# Set Go version
go:
  - 1.12.x

# Set environment variables
env:
  global:
    - GO111MODULE=on

# Install all dependencies
install:
  - make deps

# Run make targets
script:
  - make setup
  - curl -L https://git.io/vp6lP | sh
  - export PATH=`pwd`/bin:$PATH
  - make test
  - make score
  - make build-dist

# For tagged builds, create a new release
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    tags: true